### ISSUE TITLE
Arp'ing the Pi.

### ISSUE THREAD

**Issue by dschaper** [meliton/PiHole-Finder#1]
Over on https://github.com/adafruit/Adafruit-Pi-Finder they use arp to find the pi. It's a nice cross-platform solution that runs on Win/Mac/Linux. I like the flow that you're using for the pi-hole, maybe there is some code from the Pi-Finder you could use...

**Comment by meliton** [comment]
I took a quick look at their code. It's a bit bloated (a 40 meg exe) just to find a Pi. I am using VB6 since the runtimes are still supported all the way through Windows 10 and the exe's it creates will be a lot smaller. I will definitely dissect their code to see what I can use.
